import type { Metadata } from "next";
import "./globals.css";
import VisualEditsMessenger from "../visual-edits/VisualEditsMessenger";
import { AuthProvider } from "@/contexts/AuthContext";
import { DataModeProvider } from "@/contexts/DataModeContext";
import { BackendStatusProvider } from "@/contexts/BackendStatusContext";
import { ThemeProvider } from "@/hooks/use-theme";
import BackendGate from "@/components/BackendGate";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Script
          src="https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/scripts//route-messenger.js"
          strategy="afterInteractive"
          data-target-origin="*"
          data-message-type="ROUTE_CHANGE"
          data-include-search-params="true"
          data-only-in-iframe="true"
          data-debug="true"
          data-custom-data='{"appName": "YourApp", "version": "1.0.0", "greeting": "hi"}'
        />
        <ThemeProvider>
          <BackendStatusProvider>
            <BackendGate>
              <AuthProvider>
                <DataModeProvider>
                  {children}
                </DataModeProvider>
              </AuthProvider>
            </BackendGate>
          </BackendStatusProvider>
        </ThemeProvider>
        <VisualEditsMessenger />
      </body>
    </html>
  );
}
